since: 2021
homeType: simple
navType: simple
showGeneratedList: false
headerType: image_header
taxonomyHeaderType: simple
footerType: bar_with_2_columns
title: Escuela de Código PILARES-IIMAS
subtitle: Diseño de un programa de estudios para la capacitación en programación y habilidades en tecnologías de información y comunicación para la escuela de código dentro de PILARES de la Ciudad de México (SECTEI/284/2019)
headerImage:
    src: /wordcloud.png

footerLinksColumn1:
    IIMAS:
        link: "https://www.iimas.unam.mx"
        fullname: Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas
        img: iimas.png
    UNAM:
        link: "https://www.unam.mx"
        fullname: Universidad Nacional Autónoma de México
        img: unam.png

footerLinksColumn2:
    PILARES:
        link: "https://pilares.cdmx.gob.mx/inicio"
        fullname: Puntos de Innovación, Libertad, Arte, Educación y Saberes
        img: cdmx.png
    SECTEI:
        link: "https://www.sectei.cdmx.gob.mx/"
        fullname: Secretaría de Educación, Ciencia, Tecnología e Innovación
        img: cdmx.png
    xCDMX:
        link: "https://www.cdmx.gob.mx/"
        fullname: Gobierno de la Ciudad de México
        img: cdmx.png
