baseURL = "https://escuela-de-codigo-pilares-iimas.github.io/"
languageCode = "es-mx"
title = "Escuela de código PILARES-IIMAS"

# Google analytics
googleAnalytics = "G-EDCBRJ3ZCN"

# Disqus
#disqusShortname = ""

theme="eureka"

# Languages
defaultContentLanguage = "es"

summaryLength = 1

[taxonomies]
  tag = "tags"
  category = "categories"

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[languages.es]
  languageName = "Español"

  [[languages.es.menu.main]]
    url = "/members/"
    name = "Miembros"
    weight = 10

  [[languages.es.menu.main]]
    url = "/docs/"
    name = "Documentos"
    weight = 20

  [[languages.es.menu.main]]
    url = "/publications/"
    name = "Publicaciones"
    weight = 30

  [[languages.es.menu.main]]
    url = "/press/"
    name = "Media"
    weight = 40

  [[languages.es.menu.main]]
    url = "/contact/"
    name = "Contacto"
    weight = 50
